### PR TITLE
Next Later

### PR DESCRIPTION
**Pull request by TheYoBots**
Changes before this is merged:
- [x] Add New Variants.
- [x] Add Documentation for New Variants.
- [x] Fix promotion in Antiplacement.

If anything else please mention and I'll add it to the list.

### CODE REVIEW

**Comment by SriMethan** [comment]
> there is an error in antiminishogi my opponent cut my king https://liantichessdev.herokuapp.com/S1nIbhii

its the rule

**Comment by SriMethan** [comment]
you have

**Comment by SriMethan** [comment]
image

**Comment by TheYoBots** [comment]
I have to test this a bit more before merging.

**Pull request merged**
