### PR TITLE
Support Anti-antichess and Anti-antichess960

### PR DESCRIPTION
**Pull request by TheYoBots**
- Fixes to `variants.ini` file too.

Not tested yet

### CODE REVIEW

**Comment by TheYoBots** [comment]
I didn't add documentation 🤦🏻‍♂️ 

Don't merge this till documentation is added.

**Comment by cFlour** [comment]
Documentation on rules or documentation of something else?

**Comment by TheYoBots** [comment]
> Documentation on rules or documentation of something else?

On rules. It has been added now. This PR is ready to be merged.

**Comment by TheYoBots** [comment]
Not sure if a blog is required, but even if it is I won't be writing it.

**Comment by SriMethan** [comment]
Thanks!

**Pull request merged**
